services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow-network

  airflow:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - .:/opt/airflow
      - ./mlruns:/mlruns
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - PYTHONPATH=/opt/airflow
      # --- AUTHENTICATION (The FAB Way) ---
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin1234
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__CORE__FERNET_KEY=est2hiXyCL-OMEN9uWNh0ZG4qHjVGhlmCQ3L6pB3Zp0=
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - NO_PROXY=mlflow,pushgateway,localhost,127.0.0.1
      - PUSHGATEWAY_URL=http://pushgateway:9091
      - PYTHONPATH=/opt/airflow
      
    ports:
      - "8080:8080"
    # command: standalone

    command: >
      bash -c "airflow db migrate && 
               airflow api-server & 
               airflow scheduler"
    
    networks:
      - airflow-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - airflow-network
    command: >
      mlflow server 
      --backend-store-uri file:///mlruns 
      --default-artifact-root file:///mlruns 
      --host 0.0.0.0
      --allowed-hosts "*"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      - airflow
    environment:
      - PYTHONPATH=/app
    networks:         
      - airflow-network
  
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - airflow-network
  
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
    networks:
      - airflow-network
  
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - airflow-network 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    networks:
      - airflow-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - airflow-network
  
  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: streamlit_ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - airflow-network

volumes:
  postgres_data:

networks:
  airflow-network:
    driver: bridge

